---
- name: "install application"
  hosts: all
  become: yes
  become_method: sudo

  vars:
    - adminserver_jar: '../application/target/application-0-SNAPSHOT.jar'

  roles:
    - role: install_application
